COUPON_TEMPLATES = {
    "winback": {
        "name": "Geri Kazanim Kampanyasi",
        "description": "Risk altindaki musterileri geri kazanmak icin agresif indirim",
        "target_segment": "At Risk",
        "title": "Seni Ozledik!",
        "message": "Geri donmen icin sana ozel 30% indirim. Sadece 3 gun gecerli!",
        "discount_percent": 30,
        "days_valid": 3,
        "code_prefix": "WINBACK",
    },
    "vip_reward": {
        "name": "VIP Odul Kuponu",
        "description": "Sadik musterilere tesekkur ve ozel ayricalik",
        "target_segment": "High Value Loyal",
        "title": "VIP Uyemize Ozel",
        "message": "Sadakatinin karsiligi: tum urunlerde 25% indirim hediyemiz!",
        "discount_percent": 25,
        "days_valid": 30,
        "code_prefix": "VIP",
    },
    "level_up": {
        "name": "Seviye Atlama Tesviki",
        "description": "Aktif musterileri VIP seviyeye cekmek icin tesvik",
        "target_segment": "Active Customer",
        "title": "Bir Sonraki Seviyeye Gec",
        "message": "Alisverisme devam et, VIP olmana cok az kaldi! 15% indirim seni bekliyor.",
        "discount_percent": 15,
        "days_valid": 14,
        "code_prefix": "LEVEL",
    },
    "welcome": {
        "name": "Hos Geldin Hediyesi",
        "description": "Yeni musterilerin ilk alisverisini tesvik etme",
        "target_segment": "Low Engagement",
        "title": "Hos Geldin Hediyemiz",
        "message": "Ilk alisverisine ozel 15% indirim. Seni aramizda gormek guzel!",
        "discount_percent": 15,
        "days_valid": 30,
        "code_prefix": "WELCOME",
    },
    "weekend": {
        "name": "Hafta Sonu Firsati",
        "description": "Herkese genel kampanya (manuel segment sec)",
        "target_segment": None,
        "title": "Hafta Sonu Surprizi",
        "message": "Sadece bu hafta sonu, 20% indirim seni bekliyor!",
        "discount_percent": 20,
        "days_valid": 3,
        "code_prefix": "WEEKEND",
    },
}
